"""empty message

Revision ID: 48849ec288c9
Revises: 1773b5136096
Create Date: 2020-12-23 18:37:50.226775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48849ec288c9'
down_revision = '1773b5136096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('team1_pos', sa.String(length=5), nullable=True))
    op.add_column('match', sa.Column('team2_pos', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'team2_pos')
    op.drop_column('match', 'team1_pos')
    # ### end Alembic commands ###
