"""empty message

Revision ID: 99e70004589f
Revises: 592c0d222d87
Create Date: 2021-01-11 20:07:53.520996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e70004589f'
down_revision = '592c0d222d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming__match', sa.Column('uuid', sa.String(length=512), nullable=False))
    op.drop_column('upcoming__match', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming__match', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('upcoming__match', 'uuid')
    # ### end Alembic commands ###
