"""empty message

Revision ID: 1773b5136096
Revises: 
Create Date: 2020-12-23 16:32:17.757323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1773b5136096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_team', sa.String(length=120), nullable=False),
    sa.Column('first_team_score', sa.Integer(), nullable=False),
    sa.Column('second_team', sa.String(length=120), nullable=False),
    sa.Column('second_team_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('loses', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_concended', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match__player__stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('pens_made', sa.Integer(), nullable=False),
    sa.Column('pens_att', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('touches', sa.Integer(), nullable=False),
    sa.Column('pressures', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('passes_completed', sa.Integer(), nullable=False),
    sa.Column('passes_pct', sa.Integer(), nullable=False),
    sa.Column('passes_progressive_distance', sa.Integer(), nullable=False),
    sa.Column('carries', sa.Integer(), nullable=False),
    sa.Column('carry_progressive_distance', sa.Integer(), nullable=False),
    sa.Column('dribbles', sa.Integer(), nullable=False),
    sa.Column('dribbles_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=120), nullable=False),
    sa.Column('shirt_number', sa.String(length=5), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.Column('total_assists', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('match__player__stats')
    op.drop_table('team')
    op.drop_table('match')
    # ### end Alembic commands ###
