"""empty message

Revision ID: 592c0d222d87
Revises: 8bb6571650eb
Create Date: 2021-01-11 19:55:25.842772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592c0d222d87'
down_revision = '8bb6571650eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming__match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1', sa.String(length=120), nullable=False),
    sa.Column('team2', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming__match')
    # ### end Alembic commands ###
