"""empty message

Revision ID: 6fa818e39ca4
Revises: 48849ec288c9
Create Date: 2020-12-23 23:20:07.853571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa818e39ca4'
down_revision = '48849ec288c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match__player__stats', sa.Column('player_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match__player__stats', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match__player__stats', type_='foreignkey')
    op.drop_column('match__player__stats', 'player_id')
    # ### end Alembic commands ###
