"""empty message

Revision ID: 8bb6571650eb
Revises: 6fa818e39ca4
Create Date: 2020-12-24 00:20:46.442163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb6571650eb'
down_revision = '6fa818e39ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used__link',
    sa.Column('used_link', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('used_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used__link')
    # ### end Alembic commands ###
